### PR TITLE
small grammar

### PR DESCRIPTION
**Pull request by oliviagallucci**

### CODE REVIEW

**Comment by oliviagallucci** [comment]
I am unsure of why it says I removed spaces from a bunch of places (e.g., 431). I did not intend to do that. Does anyone know why this happened? I can redo this PR if needed!!! I only made a few edits.

**Comment by david-a-wheeler** [comment]
It looks like it was removing spaces at the end of lines.

That's actually a good idea, but doing that makes all the other pull requests (changes) un-mergeable. So I think we need to merge your changes that *don't impact end-of-line first.

You have to redo this PR, unfortunately.

Also: Why is "don’t" being removed? Contractions are a standard part of English. We're trying to maximize understandability, not the reading grade level. If there's an *error* or *unclear* thing we should change it, but happy->glad changes aren't worth doing.

**Comment by david-a-wheeler** [comment]
Oh, and I see all the other changes, thank you!

https://github.com/ossf/secure-sw-dev-fundamentals/pull/38 has overwhelmed my time for the course. I think we've completed that, and once that's done we can switch back.

**Comment by david-a-wheeler** [comment]
.. and by "switch back" I mean "process your PRs".

**Comment by david-a-wheeler** [comment]
Can you please redo this PR, removing all the extraneous end-of-line space changes?

I *agree* that spaces should be removed at the end of lines, but that should be done separately.

Also, don't include "happy to glad" changes. If there's an *error* we want to fix it, but uncontracting contractions, changing "&" to "and", and that sort of stuff is not an error.

**Pull request closed without merging**
