### PR TITLE
Reword availability quiz for clarity. Fixes #162

### LINKED ISSUE #162: Need to fix availability test question
Availability is a part of security. We have a test question whose purpose was to emphasize how hard it is to *always* do it, but the question goes too far & needs fixing:

image

### PR DESCRIPTION
**Pull request by david-a-wheeler**

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
@mkdolan - is this better?

**Comment by david-a-wheeler** [comment]
@SecurityCRob - any thoughts on this reword?

**Review by SecurityCRob — COMMENTED** [review]
line 394 - remove "commercial".  EVERYONE cares about availability, enterprise or not.  Also, change the listed attackers to "threat actors" or "malicious actors".  Not everything is organized crime or nation-state.  "Script kiddies" are some of the likeliest threats to availability.
line 402 - don't change to "guarantee".  That implies something like a contract.  Ensure is the better word

**Comment by david-a-wheeler** [comment]
@SecurityCRob - great points, thank you.

I'll remove "commercial" and changed "guarantee" to ensure".

Regarding the listed attackers - you're right, that's too specific. Let's make it even simpler, let's just eliminate that part of the text. All that matters is being the "target of a highly-resourced distributed denial-of-service attack (DDoS)" - it really doesn't matter *what* their motivations are.

I'll post the update. If no other comments come in, we can just merge.

**Pull request merged**
